#!/usr/bin/env bash

SESSION="ethereum-develoopment"
PROJECT_DIR="$HOME/development/ethereum/foundry-course"

tmux has-session -t "$SESSION" 2>/dev/null

if [ $? != 0 ]; then
  # Create session
  tmux new-session -d -s "$SESSION" -c "$PROJECT_DIR" -n editor

  # Window 0: Editor + Test runner
  tmux split-window -h -t "$SESSION:editor" -c "$PROJECT_DIR/src"

  # Window 1: Tests
  tmux new-window -t "$SESSION" -n test -c "$PROJECT_DIR/test"

  # Window 2: Ops / installs / configs
  tmux new-window -t "$SESSION" -n ops -c "$PROJECT_DIR"

  # Focus editor window
  tmux select-window -t "$SESSION:editor"
fi

tmux attach -t "$SESSION"

